server:
  port: 8088

spring:
  application:
    name: bz-seller-service
  datasource:
    url: jdbc:mysql://localhost:3306/security_basic?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB




